var go = [
  {
    _id: '59abcbce7aeedbb2cd151d90b13',
    name: 'problem',
    label: 'Problem',
    plural: 'problems',
    pluralL: 'Problems',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d5412e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'title',
        label: 'Title',
        _id: 'b2f7ba113d542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'body',
        label: 'Body',
        _id: 'b2f7ba113d542e961e1fde13eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'frequency',
        label: 'Frequency',
        _id: 'b2f7ba113d542e961e1fde113e8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'difficulty',
        label: 'Difficulty',
        _id: 'b2f7ba113d542e91e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'author',
        label: 'Author',
        _id: 'cb9e41f71b5106c1a101b22ba8z',
        placeholder: 'many-to-one',
        relation: { name: 'user', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isPublished',
        label: 'Published?',
        _id: 'q2f7ba11d5432e961ez1fde113eb8q1',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isSubmitted',
        label: 'Submitted?',
        _id: 'q2f7ba11d5432e961ez1fde1132b8qq',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'numLC',
        label: 'LC #',
        _id: 'q2f7ba11d5432e961ez1fde113eb8zq',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'map',
        name: 'voterIds',
        label: 'Voter IDs',
        _id: 'b2f7ba1dp14e9632ecde13cb8cb',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'editorialAuthor',
        label: 'Editor',
        _id: 'db9e41f71b5106c1a1x1b22ba8z',
        placeholder: 'many-to-one',
        relation: { name: 'user', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'editorialBody',
        label: 'Editorial Body',
        _id: 'b2f7ba113d542e91e1fde113qb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'decimal',
        name: 'editorialRating',
        label: 'Editorial Rating',
        _id: 'b2f7ba113d542e91e1fde113eb8co',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'editorialVotes',
        label: 'Editorial Votes',
        _id: 'z2f7ba113d542e91e1fde113eb8co',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'decimal',
        name: 'accepted',
        label: 'Accepted',
        _id: 'z2f7ba113d542e91e1fde113ec8co',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'decimal',
        name: 'submissions',
        label: 'Submissions',
        _id: 'z2f7ba113d542e91e1fde113eb8xo',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'decimal',
        name: 'acceptanceRate',
        label: 'Acceptance Rate',
        _id: 'z2f7ba113d542e91e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'array',
        name: 'testSuite',
        label: 'Test Suite',
        _id: 'z2f7ba113d542e91e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'topics',
        label: 'Topics',
        _id: 'cb9e41f71b5106c1a101b22baxc',
        relation: { name: 'topic', type: 'mtm' },
      },
      {
        validators: [],
        validations: [],
        type: 'array',
        name: 'hints',
        label: 'Hints',
        _id: 'db9e41f71b5106c1a101b22ba8c',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'array',
        name: 'constraints',
        label: 'Constraints',
        _id: 'db9e41f71b5106c1a101b22ba89',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7ae2edbzcd151d90zb1x',
    name: 'submission',
    label: 'submission',
    plural: 'submissions',
    pluralL: 'Submissions',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d542e1961e1fdse113eb8zcz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'body',
        label: 'Body',
        _id: 'b2f7za11d5412e2961e1fde113eb8czz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'title',
        label: 'Title',
        _id: 'b2f7ba21d15412e961e1fde113eb8czz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'explanation',
        label: 'Explanation',
        _id: 'b2f7ba113d5412e961e2fde113eb8czz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'language',
        label: 'Language',
        _id: 'b2f7ba11d5412e961e1fd1e113e38czz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'notes',
        label: 'Notes',
        _id: 'h2f7ba11d54412e961e1fde113xb8czz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'user',
        label: 'User',
        _id: 'db9e41f7e1b51016c1a1x1b22ba8x',
        placeholder: 'many-to-one',
        relation: { name: 'user', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'comments',
        label: 'Comments',
        _id: 'cb9e4df7115121061a110b22ba8x',
        placeholder: 'one-to-many',
        relation: { name: 'comment', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'problem',
        label: 'Problem',
        _id: 'db9e41f71b5106csa11x1b22ba8z',
        placeholder: 'many-to-one',
        relation: { name: 'problem', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'contest',
        label: 'Contest',
        _id: 'db9e41f71b51106c1a1t1b22ba8z',
        placeholder: 'many-to-one',
        relation: { name: 'contest', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        name: 'timeSubmitted',
        label: 'Submit Time',
        _id: 'dae869bbcacb21ba1defc6ae1',
        relation: { type: null, name: null },
        type: 'dateTime',
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isPublished',
        label: 'Published?',
        _id: 'b2f7ba1d514e963cfde13eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isShared',
        label: 'Shared?',
        _id: 'b2f7ba1d54e2x63efde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isContest',
        label: 'Contest?',
        _id: 'b2f7ba1d1z4e963efde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'penalty',
        label: 'Penalty',
        _id: 'b2f7ba1dp41e963efde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'numVotes',
        label: '# Votes',
        _id: 'b2f7ba1d2p4e963efde13ex8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'numComments',
        label: '# Comments',
        _id: 'b2f7ba1d1p4e963ecde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'decimal',
        name: 'runTime',
        label: 'Run Time',
        _id: 'b2f7ba1dp4e963ec2dex3eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'decimal',
        name: 'beats',
        label: 'Beats',
        _id: 'b2f7ba1dp4e9163ecde13cb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'map',
        name: 'voterIds',
        label: 'Voter IDs',
        _id: 'b2f7ba1dp4e9632ecde13cb8cb',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'topics',
        label: 'Topics',
        _id: 'cb9e4df7115211061a110bx2ba8x',
        placeholder: 'many-to-many',
        relation: { name: 'topic', type: 'mtm' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedbbcd15d90b13',
    name: 'article',
    label: 'Article',
    plural: 'articles',
    pluralL: 'Articles',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'type',
        label: 'Type',
        _id: 'b2f7ba1d54e96e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'title',
        label: 'Title',
        _id: 'b2f7ba1d54e96efde143eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'caption',
        label: 'Caption',
        _id: 'b2f7ba1d54e96efde313eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'body',
        label: 'Body',
        _id: 'b2f7ba1d54e96efde213eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'link',
        label: 'Link',
        _id: 'b2f7ba1d54e96efd1e13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'urlCoverImg',
        label: 'Cover Img',
        _id: 'b2f7ba1d54e96ef8de13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'urlVideo',
        label: 'Video',
        _id: 'b2f7ba1d54e96efd7e13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'language',
        label: 'Language',
        _id: 'b2f7ba1d54e966efde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'numComments',
        label: 'Number Comments',
        _id: 'b2f7ba1d54e96ef5de13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'numVotes',
        label: 'Number Votes',
        _id: 'b2f7ba1d54e496efde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isPublished',
        label: 'Published?',
        _id: 'b2f7ba1d54e963efde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isOriginal',
        label: 'Original?',
        _id: 'b2f7ba1d54e962efde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'author',
        label: 'Author',
        _id: 'cb9e4df71b51061a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'user', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'comments',
        label: 'Comments',
        _id: 'cb9e4df711521061a110b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'comment', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'map',
        name: 'voterIds',
        label: 'Voter IDs',
        _id: 'b2f7ba1sp4e9632ecde13cb8cb',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeed2bbcd151d90b13',
    name: 'post',
    label: 'Post',
    plural: 'posts',
    pluralL: 'Posts',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'string',
        name: '_id',
        _id: 'b2f7ba1d542e1961e1fdde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'title',
        label: 'Title',
        _id: 'b2f7ba11d5432e961ez1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'body',
        label: 'Body',
        _id: 'q2f7ba11d5432e961ez1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isPublished',
        label: 'Published?',
        _id: 'q2f7ba11d5432e961ez1fde113eb8qq',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'numVotes',
        label: '# Votes',
        _id: 'q217ba11d5432e961ez1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'numViews',
        label: '# Views',
        _id: 'q2f2ba11d5432e961ez1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'numComments',
        label: '# Comments',
        _id: 'q2f7ba11d3432e961ez1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'dateTime',
        name: 'timeSubmitted',
        label: 'Time Submitted',
        _id: 'q2f7ba11d5432e961ez1fde113eb8qz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'user',
        label: 'User',
        _id: 'cb9e41f71b5106c1a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'user', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'comments',
        label: 'Comments',
        _id: 'cb9e41f71b51061ba101b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'comment', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'topics',
        label: 'Topics',
        _id: 'cb9e41f71b51061a10a1b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'topic', type: 'mtm' },
      },
      {
        validators: [],
        validations: [],
        type: 'map',
        name: 'voterIds',
        label: 'Voter IDs',
        _id: 'b2f7ba11dp4e9632ecde13cb8cb',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedbbcd1511d90b13',
    name: 'contest',
    label: 'Contest',
    plural: 'contests',
    pluralL: 'Contests',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d542e9611e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        label: 'Name',
        _id: 'b2f7ba11d5242e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'body',
        label: 'Body',
        _id: 'b2f7ba11d5242e61e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'title',
        label: 'Title',
        _id: 'b2f7ba11d5242e961e1fd113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'company',
        label: 'Company',
        _id: 'cbe41f71b510612aa01b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'company', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'sponsor',
        label: 'Sponsor',
        _id: 'cbe41fa1b510612a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'sponsor', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'dateTime',
        name: 'timeStart',
        label: 'Start Time',
        _id: 'b2f7ba111d5342e961e1fde113ez8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'dateTime',
        name: 'timeEnd',
        label: 'End Time',
        _id: 'b2f7ba111d5342e961e1fda113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'problem',
        label: 'Problems',
        _id: 'cbe41fa1b51612a101b22ba8c',
        placeholder: 'many-to-many',
        relation: { name: 'problem', type: 'mtm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'submissions',
        label: 'Submissions',
        _id: 'cbe4fa1b510612a101b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'submission', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'users',
        label: 'Users',
        _id: 'cbe41f1b510612a101b22ba8c',
        placeholder: 'many-to-many',
        relation: { name: 'user', type: 'mtm' },
      },
    ],
  },
  {
    _id: 'fb80c35deae8c1d25f4acbbd',
    name: 'user',
    plural: 'users',
    label: 'User',
    pluralL: 'Users',
    attributes: [
      {
        name: '_id',
        type: 'text',
        _id: '5f6ab0bbfb54cf51242ddb6a',
        validators: [],
        validations: [],
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'email',
        label: 'Email',
        _id: '0cadf0cb95bd08874aeb398e',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        name: 'firstName',
        label: 'First Name',
        type: 'string',
        _id: '5aab0a1efa84976ab3afea9e',
        validators: [],
        validations: [],
        relation: { name: null, type: '' },
      },
      {
        name: 'lastName',
        label: 'Last Name',
        type: 'string',
        _id: '040e9eeeec2ae4eb4fd1946e',
        validators: [],
        validations: [],
        relation: { name: null, type: '' },
      },
      {
        name: 'age',
        type: 'integer',
        label: 'Age',
        _id: 'dcb9b448e5bce7c8bdea1ece',
        validators: [],
        validations: [],
        relation: { name: null, type: '' },
      },
      {
        name: 'status',
        label: 'Status',
        type: 'enumerator',
        _id: '077cb5ead63ef967d1adcc2c',
        validators: [],
        validations: [],
        options: 'open,closed,pending',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        name: 'city',
        _id: 'a3aef9ecb114efde29c0aed6',
        relation: { type: null, name: null },
        type: 'string',
        label: 'City',
      },
      {
        validators: [],
        validations: [],
        name: 'country',
        _id: 'fdbd3ba3d4f1bbbbc7cfcfca',
        relation: { type: null, name: null },
        type: 'string',
        label: 'Country',
      },
      {
        validators: [],
        validations: [],
        name: 'dob',
        label: 'DOB',
        _id: 'dae869bbcacb1ba1defc6ae1',
        relation: { type: null, name: null },
        type: 'date',
      },
      {
        validators: [],
        validations: [],
        name: 'status',
        label: 'Status',
        _id: 'deaa69fd5793cf29f62da810',
        relation: { type: null, name: null },
        type: 'enumerator',
        options: 'pending,active,closed,deactivated,blocked',
      },
      {
        validators: [],
        validations: [],
        name: 'username',
        label: 'Username',
        _id: 'c16ee76ee14ce9f8c818dca3',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'urlAvatar',
        label: 'AvatarURL',
        _id: 'c16ee76ee14ce9f8c81x8dca3',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'urlPaypal',
        label: 'PaypalURL',
        _id: 'c16ee76ee14ce9f8c1818dca3',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'urlGithub',
        label: 'GithubURL',
        _id: 'c16ee76ee14ce92f8c818dca3',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'urlLinkedIn',
        label: 'LinkedInURL',
        _id: 'c16ee76ee14ce39f8c818dca3',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'urlPortfolio',
        label: 'PortfolioURL',
        _id: 'c16ee76ee14c4e9f8c818dca3',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'urlCSProfile',
        label: 'urlCSProfile',
        _id: 'c16ee765ee14ce9f8c818dca3',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'urlSites',
        label: 'SiteURLs',
        _id: 'c16ee765ee14ce9f8c818xdca3',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'views',
        label: '# Views',
        _id: 'c16ee765ee14ce9f8c818xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'discuss',
        label: '# Discuss',
        _id: 'c16ee7165ee14ce9f8c818xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'solutions',
        label: '# Solutions',
        _id: 'c11ee765ee14ce9f8c818xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'reputation',
        label: 'Reputation',
        _id: 'd16ee765ee14ce9f8c818xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'contestRating',
        label: 'Contest Rating',
        _id: 'd16ee7615ee14ce9f8c818xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'globalRanking',
        label: 'Global Ranking',
        _id: 'd16ee765ee14ce9f81c818xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'attended',
        label: '# Attended',
        _id: 'd16ee765ee14ce9f8c8118xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'startYear',
        label: 'Start Year',
        _id: 'd16ee765ee14ce9f8c818xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'numSubmissions',
        label: '# Submissions',
        _id: 'd16ee765ee14ce29f8c818xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'numAcceptedProblems',
        label: '# Accepted Problems',
        _id: 'd16ee765ee14ce9f8c818xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'numSubmittedProblems',
        label: '# Submitted Problems',
        _id: 'd16ee765ee14ce9zf8c818xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'numAcceptedSubmissions',
        label: '# Accepted Submissions',
        _id: 'd16ee765ee14ce9f8c818xdca3',
        relation: { type: null, name: null },
        type: 'integer',
      },
      {
        validators: [],
        validations: [],
        name: 'gender',
        label: 'Gender',
        _id: 'd16ee7165ee14ce9f8c818xdca3',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'top',
        label: 'Top',
        _id: 'd16ee765ee14ce9f82818xdca3',
        relation: { type: null, name: null },
        type: 'decimal',
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'submissions',
        label: 'Submissions',
        _id: 'cb9e4df71152106x1a110b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'submission', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'posts',
        label: 'Posts',
        _id: 'cb9e4df711521c061a110b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'post', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'contests',
        label: 'Contests',
        _id: 'cb9e4df71152106v1a110b22ba8c',
        placeholder: 'many-to-many',
        relation: { name: 'contest', type: 'mtm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'comments',
        label: 'Comments',
        _id: 'cb9e4df711521061za110b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'comment', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'badgeItem',
        label: 'Badge Items',
        _id: 'cb9e4df711521061a110b22xba8c',
        placeholder: 'one-to-many',
        relation: { name: 'badgeItem', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'articles',
        label: 'Articles',
        _id: 'cb9e4df711521061a110b2c2ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'article', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'problems',
        label: 'Problems',
        _id: 'cb9e4df711521061av110b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'problem', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'map',
        name: 'meta',
        label: 'Meta Data',
        _id: 'cb9e4df711521061av110b22bxa8c',
        placeholder: 'Meta Data',
        relation: { name: 'problem', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'badges',
        label: 'Badges',
        _id: 'cb9e4df711521061av110b22bxxa8c',
        relation: { name: 'badge', type: 'mtm' },
      },
    ],
  },
  {
    _id: '59abcbce73aeedbbcd151d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'Badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d5242e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        label: 'Name',
        _id: 'b2f7ba111d542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'urlImg',
        label: 'ImgURL',
        _id: 'b2f7ba111d542961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'year',
        label: 'Year',
        _id: 'b2f7ba111d52e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'month',
        label: 'Month',
        _id: 'b2f7ba111d54e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'users',
        label: 'Users',
        _id: 'cb9e4df711521061av110b22bxxxa8c',
        relation: { name: 'user', type: 'mtm' },
      },
    ],
  },
  {
    _id: '59abcbce73aeedbbcd151d910b13',
    name: 'badgeItem',
    label: 'BadgeItem',
    plural: 'BadgeItems',
    pluralL: 'BadgeItems',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d52422e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'date',
        name: 'date',
        label: 'Date',
        _id: 'b2f7ba111d5342e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'month',
        label: 'Month',
        _id: 'b2f7ba111d35342e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'year',
        label: 'Year',
        _id: 'b2f7ba1112d5342e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'user',
        label: 'User',
        _id: 'cb9e41f71b51061a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'user', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'badge',
        label: 'Badge',
        _id: 'cb9e41xf71b51061a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'badge', type: 'mto' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedbb3cd151d90b13',
    name: 'comment',
    label: 'Comment',
    plural: 'comments',
    pluralL: 'Comments',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d542e2961e1fde1113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'body',
        label: 'Body',
        _id: 'b2f7ba11d5142961e12fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'code',
        label: 'Code',
        _id: 'b2f7ba11d5142961e12fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'user',
        label: 'User',
        _id: 'cb9e41f71b510612a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'user', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'post',
        label: 'Post',
        _id: 'cbe41f71b510612a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'post', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'article',
        label: 'Article',
        _id: 'cb941f71b510612a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'article', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'comment',
        label: 'Comment',
        _id: 'cb91e41f71b510612a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'comment', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'comments',
        label: 'Comments',
        _id: 'cb91e41f71b51612a101b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'comment', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'problem',
        label: 'Problem',
        _id: 'cb1e41f71b510612a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'problem', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'submission',
        label: 'Submission',
        _id: 'cb9e41f71b510612a101b22baxc',
        placeholder: 'many-to-one',
        relation: { name: 'submission', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'map',
        name: 'voterIds',
        label: 'Voter IDs',
        _id: 'b2f7ba1dp4e9632ecze13cb8cb',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedbbcd151d190b13',
    name: 'company',
    label: 'Company',
    plural: 'companies',
    pluralL: 'Companies',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d542e9611e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        label: 'Name',
        _id: 'b2f7ba11d542e9621e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'industry',
        label: 'Industry',
        _id: 'b2f7ba11d542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'founded',
        label: 'Founded',
        _id: 'b2f7ba11d542e962e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'location',
        label: 'Location',
        _id: 'b2f7ba11542e962e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'urlAvatar',
        label: 'AvatarURL',
        _id: 'b2f7ba11d52e962e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'teamSize',
        label: 'Team Size',
        _id: 'b2f7ba11d52e962e1de113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'array',
        name: 'industries',
        label: 'Industries',
        _id: 'b2f7ba11d52e962ede113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'array',
        name: 'founders',
        label: 'Founders',
        _id: 'b2f7ba11d52e92ede113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'array',
        name: 'technologies',
        label: 'Technologies',
        _id: 'b2f7ba11d52e9621de113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'jobs',
        label: 'Jobs',
        _id: 'cbe4fa1b530612a101b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'job', type: 'otm' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedbbcd1521d90b13',
    name: 'job',
    label: 'Job',
    plural: 'jobs',
    pluralL: 'Jobs',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'string',
        name: '_id',
        _id: 'b2f7ba1d542e9621e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'title',
        label: 'Title',
        _id: 'b2f7ba11d5421e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'caption',
        label: 'Caption',
        _id: 'p2f7ba11d5421e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'location',
        label: 'Location',
        _id: 'b2f7ba11d5421e961e1fde113eg8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'type',
        label: 'Type',
        _id: 'b2f7ba11d5521e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'description',
        label: 'Description',
        _id: 'b2f7bq11d5421e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'experience',
        label: 'Experience',
        _id: 'b2f7bb11d5421e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'project',
        label: 'Project',
        _id: 'b217ba11d5421e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'requirements',
        label: 'Requirements',
        _id: 'b2f71ba11d5421se961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'whoAreYou',
        label: 'Who are you',
        _id: 'b2f7b1a11d5421e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'equity',
        label: 'Equity',
        _id: 'b2f7ba11d5421e9611e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'benefits',
        label: 'Benefits',
        _id: 'b2f17ba11d5421e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isRemote',
        label: 'Remote?',
        _id: 'b2f17ba11w5421e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'array',
        name: 'technologies',
        label: 'Technologies',
        _id: 'b2f17ba11d5421e96qe1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'company',
        label: 'Company',
        _id: 'cbe41f71b510612a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'company', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'user',
        label: 'User',
        _id: 'dbe41f71b510612a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'user', type: 'mto' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedb1bcd151d90b13',
    name: 'participant',
    label: 'Participant',
    plural: 'participants',
    pluralL: 'Participants',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d5242e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        label: 'Name',
        _id: 'b2f7ba111d542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'contest',
        label: 'Contest',
        _id: 'abe41f1b510612a101b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'contest', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'user',
        label: 'User',
        _id: 'abe41f1b510612a101b22ba8d',
        placeholder: 'many-to-one',
        relation: { name: 'user', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'submission',
        label: 'Submissions',
        _id: 'cbe4fa1b510612a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'submissions', type: 'mto' },
      },
      {
        name: 'score',
        label: 'Score',
        type: 'integer',
        _id: 'dcb9b448e15bce7c8bdea1ece',
        validators: [],
        validations: [],
        relation: { name: null, type: '' },
      },
      {
        name: 'rank',
        label: 'Rank',
        type: 'integer',
        _id: 'dcb9b448e25bce7c8bdea1ece',
        validators: [],
        validations: [],
        relation: { name: null, type: '' },
      },
      {
        name: 'rating',
        label: 'Rating',
        type: 'integer',
        _id: 'dcb9b4483e5bce7c8bdea1ece',
        validators: [],
        validations: [],
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'dateTime',
        name: 'time',
        label: 'Time',
        _id: 'b2f7ba111d5342e961e1fde113ez8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeed2bbcd151d90b13',
    name: 'guide',
    label: 'Guide',
    plural: 'guides',
    pluralL: 'Guides',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d1542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'title',
        label: 'Title',
        _id: 'b2f7ba11d25442e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'body',
        label: 'Body',
        _id: 'b2f7ba11d25432e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'caption',
        label: 'Caption',
        _id: 'b2f7ba11d25422e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'description',
        label: 'Description',
        _id: 'b2f7ba11d25142e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'topics',
        label: 'Topics',
        placeholder: 'many-to-many',
        _id: 'b2f1ba11d25142e961e1fde113eb8cz',
        relation: { name: 'topic', type: 'mtm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'problems',
        label: 'Problems',
        placeholder: 'many-to-many',
        _id: 'b2f1ba11x25142e961e1fde113eb8cz',
        relation: { name: 'problem', type: 'mtm' },
      },
    ],
  },
  {
    _id: '59abcbce7ae1edbbcd151d90b13',
    name: 'notification',
    label: 'Notification',
    plural: 'notifications',
    pluralL: 'Notifications',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7bb1d5421e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'title',
        label: 'Title',
        _id: 'b2f7ba11d5422e961e11de113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'body',
        label: 'Body',
        _id: 'b5f7ba11d5422e961e11de113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'type',
        label: 'Type',
        _id: 'b2f7ba11d5422e961e11de113ep8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'points',
        label: 'Points',
        _id: 'b2f7ba11d5422e961e11de113ep8co',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isPublished',
        label: 'Published?',
        _id: 'b2f7ba11d5422e961e11de413ep8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'date',
        name: 'date',
        label: 'Date',
        _id: 'b2f7ba11d542e961e11de113ep8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeed1bbcd151d90b13',
    name: 'notificationItem',
    label: 'NotificationItem',
    plural: 'notificationItems',
    pluralL: 'NotificationItems',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d5242e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'icon',
        label: 'Icon',
        _id: 'b2f7ba1111d542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isRead',
        label: 'Read?',
        _id: 'b2f7ba111d542e2961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'points',
        label: 'Points',
        _id: 'b2f7ba111d542e9631e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'dateTime',
        name: 'date',
        label: 'Date',
        _id: 'b2f7ba111d542e9614e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'notifiableId',
        label: 'NotifiableId',
        _id: 'b2f7ba111d542e9615e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'notifiableType',
        label: 'NotifiableType',
        _id: 'b2f7ba111d542e961e61fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'type',
        label: 'Type',
        _id: 'b2f7ba111d542e961e1fde7113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'notification',
        label: 'Notification',
        _id: 'b2f7ba111d542e961e1f8de113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'user',
        label: 'User',
        _id: 'cb9e41f71b51061a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'user', type: 'mto' },
      },
    ],
  },
  {
    _id: '59abczce7ae2e6dbbcd151d90b13',
    name: 'topic',
    label: 'Topic',
    plural: 'topics',
    pluralL: 'Topics',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d5425e1961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        label: 'Name',
        _id: 'b2f7ba111d5412e5961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'posts',
        label: 'Posts',
        _id: 'cb9e4df7115210641a110b22ba8x',
        placeholder: 'many-to-many',
        relation: { name: 'post', type: 'mtm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'guides',
        label: 'Guides',
        _id: 'cb9e4df7115210631a110b22ba8x',
        placeholder: 'many-to-many',
        relation: { name: 'guide', type: 'mtm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'problems',
        label: 'Problems',
        _id: 'cb9e4df711521061a1120b22ba8x',
        placeholder: 'many-to-many',
        relation: { name: 'problem', type: 'mtm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'contests',
        label: 'Contests',
        _id: 'cb9e4df711521061a110b221ba8x',
        placeholder: 'many-to-many',
        relation: { name: 'contest', type: 'mtm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'submissions',
        label: 'Submissions',
        _id: 'cb9e4df711521061a110bx221ba8x',
        placeholder: 'many-to-many',
        relation: { name: 'submission', type: 'mtm' },
      },
    ],
  },
  {
    name: 'wizard',
    label: 'Wizards',
    plural: 'wizards',
    pluralL: 'Wizards',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'email',
        label: 'email',
        _id: '0cadf0cb95bd08874aeb398e',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'firstName',
        label: 'firstName',
        _id: 'c6a9dffe4d4574ddbad05818',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'lastName',
        label: 'lastName',
        _id: 'e79282eed6b17b7629eafc24',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'dob',
        label: 'dob',
        _id: 'd63a922e7cae4ece7deceb00',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'map',
        name: 'location',
        label: 'location',
        _id: '9f4c15fb8d0bf4c3e4b58e93',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'jobTitle',
        label: 'jobTitle',
        _id: '4a29f55871dc0528590e29ba',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'industry',
        label: 'industry',
        _id: '28ae4419cfef12dfe65a3f2d',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'enumerator',
        name: 'patronus',
        label: 'patronus',
        options: 'a,b,c,d,e',
        placeholder: 'a,b,c,d,e',
        _id: 'ab83a9bbdb9f99eb0fabaa1e',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'decimal',
        name: 'potions',
        label: 'potions',
        _id: '6e226491eb3ead4c7aba7bb1',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'charms',
        label: 'charms',
        _id: 'fcae3a6cdf4ef47ae958c9d1',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'dada',
        label: 'dada',
        _id: 'f08c706bcb3ccfb7edbb2ecd',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'sex',
        label: 'sex',
        _id: '634b82adabe6f7147de9caa5',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'avatarUrl',
        label: 'avatarUrl',
        _id: '7f93acd7ad7eef3ae3cab80f',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'enumeratorMulti',
        name: 'topSpells',
        label: 'topSpells',
        options:
          'jinxes, hexes, charms, curses, spells, counters, healing, transfigurations',
        placeholder:
          'jinxes, hexes, charms, curses, spells, counters, healing, transfigurations',
        _id: 'ff6cbccefe22cdf2ea2f637b',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'enumerator',
        name: 'bookAppearances',
        label: 'bookAppearances',
        _id: 'f945cbcd3c24b1e6efce9f7c',
        placeholder: '1,2,3,4,5,6,7,8',
        options: '1,2,3,4,5,6,7,8',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'enumerator',
        name: 'house',
        options: 'gryffindor, slytherin, hufflepuff, ravenclaw, unknown',
        placeholder: '',
        label: 'house',
        _id: 'e7c6bfa32dd8c9ad822c0ea3',
        relation: { name: null, type: '' },
      },
    ],
    _id: '7a43da35ea0ada4403ebbf4f',
  },
  {
    name: 'foo',
    label: 'Foo',
    plural: 'foos',
    pluralL: 'Foos',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'fooBoolean',
        label: 'Foo Boolean',
        _id: '6dcc79ee7eb4f14dc1e0ce4b',
        placeholder: 'foo boolean placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'fooString',
        label: 'Foo String',
        _id: '3d00e44df2b3bb22da6723cb',
        placeholder: 'foo string placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'fooText',
        label: 'Foo Text',
        _id: 'bcbbfc4c1547d1627cd15fe2',
        placeholder: 'foo text placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'fooInteger',
        label: 'Foo Integer',
        _id: '25baeb5cb6b90eb3dd68ce9d',
        placeholder: 'foo integer placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'decimal',
        name: 'fooDecimal',
        label: 'Foo Decimal',
        _id: 'b0dc5b861bf1cccdffa63ae4',
        placeholder: 'foo decimal placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'date',
        name: 'fooDate',
        label: 'Foo Date',
        _id: 'ad24804ffbd5a7932701d5f1',
        placeholder: 'foo date placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'dateTime',
        name: 'fooDateTime',
        label: 'Foo Date Time',
        _id: '10ebc11ec20a1cac1e1abdfe',
        placeholder: 'foo datetime placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'array',
        name: 'fooArray',
        label: 'Foo Array',
        _id: '2acf20585fe9beac06d823d8',
        placeholder: 'foo array placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'map',
        name: 'fooMap',
        label: 'Foo Map',
        _id: '6fbadff36a541a3730eceabc',
        placeholder: 'foo map placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'enumerator',
        name: 'fooEnumerator',
        label: 'Foo Enumerator',
        _id: 'df3dab2f94babfb3eb2decef',
        placeholder: 'a,b,c,',
        relation: { name: null, type: '' },
        options: 'a,b,c',
      },
      {
        validators: [],
        validations: [],
        type: 'enumeratorMulti',
        name: 'foodEnumeratorMulti',
        label: 'Foo Enum Multi',
        _id: 'd35baeae0fdea2f0aaba41ad',
        placeholder: 'a,b,c',
        relation: { name: null, type: '' },
        options: 'a,b,c',
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'fooOTM',
        label: 'Foo OTM',
        _id: '3b91bb9236bf6ae409babfed',
        placeholder: 'one-to-many',
        relation: { name: 'related', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'fooMTO',
        label: 'Foo MTO',
        _id: 'cb9e4df7b51061a10b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'related', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'fooOTO',
        label: 'Foo OTO',
        _id: '9ba3dbf02fd484ec618a9e8f',
        placeholder: 'one-to-one',
        relation: { name: 'related', type: 'oto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'fooMTM',
        label: 'Foo MTM',
        _id: 'ec2ef0ec3cd71cfecabfbcd4',
        placeholder: 'many-to-many',
        relation: { name: 'related', type: 'mtm' },
      },
    ],
    _id: '8c5a8f9659e0f926cf0da3ff',
  },
]
